from dataclasses import dataclass
from types import ModuleType
from typing import Any, Dict
import os
import re
import sys

from triton.backends.compiler import BaseBackend, GPUTarget, Language
from triton._C.libtriton import ir, passes, llvm, nvidia


# ---------------------------------------------------------------------------
# Debug helpers — dump triton-opt commands for manual pass-by-pass replay
# ---------------------------------------------------------------------------

def _im_debug() -> bool:
    return os.environ.get("TRITON_IM_DEBUG", "") == "1"


def _triton_opt_path() -> str:
    """Best-effort locate the triton-opt binary in the build tree."""
    import glob
    import triton._C.libtriton as _lib
    # The source tree root: ...triton/python/triton/_C → ...triton/
    triton_root = os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(_lib.__file__)))))
    # Look in build/*/bin/triton-opt (the cmake build directory)
    pattern = os.path.join(triton_root, "build", "*", "bin", "triton-opt")
    candidates = glob.glob(pattern)
    if candidates:
        return candidates[0]
    return "triton-opt"  # fallback — assume on PATH


def _dump_stage(mod_or_str, stage: str, filename: str) -> str:
    """Write an IR snapshot to im_debug/<filename> and return its path."""
    outdir = os.path.join(os.getcwd(), "im_debug")
    os.makedirs(outdir, exist_ok=True)
    ir_text = mod_or_str if isinstance(mod_or_str, str) else str(mod_or_str)
    path = os.path.join(outdir, filename)
    with open(path, "w") as f:
        f.write(ir_text)
    return path


def _dump_commands(stages: list[dict]) -> None:
    """Write im_debug/commands.sh with copy-pasteable triton-opt pipelines."""
    outdir = os.path.join(os.getcwd(), "im_debug")
    os.makedirs(outdir, exist_ok=True)
    triton_opt = _triton_opt_path()
    path = os.path.join(outdir, "commands.sh")
    with open(path, "w") as f:
        f.write("#!/usr/bin/env bash\n")
        f.write("# IM Backend — pass pipeline commands\n")
        f.write("# Generated by TRITON_IM_DEBUG=1\n")
        f.write("#\n")
        f.write("# Copy any command below and run it to reproduce that stage.\n")
        f.write("# Remove passes from the pipeline to inspect intermediate IR.\n")
        f.write(f'\nTRITON_OPT="{triton_opt}"\n')
        for s in stages:
            f.write(f'\n# ── {s["title"]} ──\n')
            if s.get("note"):
                f.write(f'# {s["note"]}\n')
            f.write(f'# input:  {s["input"]}\n')
            f.write(f'# output: {s["output"]}\n')
            pipeline = ",".join(s["passes"])
            f.write(f'"$TRITON_OPT" {s["input"]} \\\n')
            f.write(f"  -pass-pipeline='builtin.module({pipeline})'\n")
    os.chmod(path, 0o755)
    # Print to stderr so the user sees it.
    print(f"[IM debug] commands → {path}", file=sys.stderr)
    for s in stages:
        print(f"  {s['title']}: {s['input']} → {s['output']}  "
              f"({len(s['passes'])} passes)", file=sys.stderr)


@dataclass(frozen=True)
class IMOptions:
    num_banks: int = 16   # parallel PIM banks (HBM-PIM default: 4 BG × 4 banks)
    num_warps: int = 1    # always 1 for IM (no warp hierarchy)
    num_ctas: int = 1
    num_stages: int = 2
    enable_fp_fusion: bool = True
    launch_cooperative_grid: bool = False
    sanitize_overflow: bool = True
    default_dot_input_precision: str = "ieee"
    allowed_dot_input_precisions: tuple[str, ...] = ("ieee",)
    max_num_imprecise_acc_default: int = 0
    debug: bool = False
    backend_name: str = "im"
    instrumentation_mode: str = ""
    arch: str = "hbm-pim"
    skip_passes: tuple[str, ...] = ()  # pass names to skip (for ablation)
    # User schedule for im-operand-residency-layout, as MLIR dictionary text
    # keyed by kernel operand index, e.g.
    #   '{arg1 = {reuse_class = "BroadcastReplicate", resident = true}}'
    # Empty means the classifier decides everything.
    im_schedule: str = ""
    # Which tensor axis carries the banks (rewrite-im-layout). -1 keeps the
    # upstream choice. Bounds operand amortisation: emitted traffic is
    # MACs*banks/BLOCK[bank_axis], so a shape whose bank axis is small can never
    # amortise however the tile is picked.
    im_bank_axis: int = -1
    # Bank-group interleave (whole-kernel address mapping). Compiler-emitted so the
    # decision lives in the artifact rather than a runtime env var.
    im_bg_interleave: bool = False
    # Placement policy, stated here so the artifact records it instead of the runtime
    # picking a default. "interleaved" spreads consecutive elements across banks;
    # "striped" is the legacy compact/row-stripe scheme. The alignment rule decides
    # where each tensor starts: "dq" packs tensors so they share rows but land on
    # different banks, "global-row" starts every tensor at bank 0, which hot-spots
    # small tensors and measured 3.2x worse on one conv shape. Both are levers now.
    # Persistent kernel: the grid stops being the work decomposition and one program
    # instance loops over several tiles. Marks the module so im-tile-boundary knows
    # which loop to signal; without it the trace runtime sees the whole replay as one
    # dispatch and cross-tile re-reads collapse to nothing.
    im_persistent: bool = False
    im_layout_scheme: str = "interleaved"
    im_placement_align: str = "dq"
    # Values one DRAM row holds per bank (num_cols * dq_bits). Hardware geometry the
    # compiler does not choose but must STATE, because the SIMDRAM occupancy charge
    # divides by it. 0 = unstated, and the runtime then keeps its own.
    im_row_values: int = 0
    # Bits one column command moves, which is what a vector access is sized against.
    # Differs by target: HBM-PIM moves prefetch*dq = 256, SIMDRAM's column is a
    # bit-serial slot of dq = 128. 0 = unstated, and the lowering keeps its default.
    im_dq_bits: int = 0
    # Lanes per tensor axis, e.g. "4,8" = 4 banks on axis 0 and 8 on axis 1. Empty
    # keeps the all-lanes-on-one-axis placement. The product must be num_banks. A
    # split over an axis the kernel reduces is refused by rewrite-im-layout: that is
    # a cross-bank reduction, and the partials have to leave the kernel instead.
    im_bank_split: str = ""

    def hash(self):
        skip_tag = ",".join(sorted(self.skip_passes)) if self.skip_passes else "none"
        # The schedule changes emitted attrs, so it has to key the cache.
        sched_tag = self.im_schedule or "none"
        return (f"im-{self.arch}-b{self.num_banks}-c{self.num_ctas}"
                f"-skip:{skip_tag}-sched:{sched_tag}-bax:{self.im_bank_axis}"
                f"-bgi:{int(self.im_bg_interleave)}"
                f"-lay:{self.im_layout_scheme}-align:{self.im_placement_align}"
                f"-persist:{int(self.im_persistent)}-row:{int(self.im_row_values)}"
                f"-dq:{int(self.im_dq_bits)}-split:{self.im_bank_split or 'none'}")


class IMBackend(BaseBackend):
    @staticmethod
    def supports_target(target: GPUTarget):
        return target.backend == "im"

    def __init__(self, target: GPUTarget) -> None:
        super().__init__(target)
        self.binary_ext = "llir"

    def hash(self) -> str:
        return f"im-{self.target.arch}"

    def parse_options(self, opts) -> Any:
        args = {
            "arch": str(self.target.arch),
            # GPUTarget.warp_size carries num_banks (the IM-meaningful field).
            "num_banks": self.target.warp_size,
            "num_warps": 1,
            "num_ctas": int(opts.get("num_ctas", 1)),
            "num_stages": int(opts.get("num_stages", 2)),
        }
        for key in IMOptions.__dataclass_fields__.keys():
            if key in opts and opts[key] is not None:
                args[key] = opts[key]
        return IMOptions(**args)

    def pack_metadata(self, metadata):
        return (
            getattr(metadata, "num_warps", 1),
            getattr(metadata, "num_ctas", 1),
            getattr(metadata, "shared", 0),
        )

    def get_codegen_implementation(self, options):
        return {}

    def get_module_map(self) -> Dict[str, ModuleType]:
        return {}

    def load_dialects(self, ctx):
        # The shared FuncOpConversion (TritonGPUToLLVM) references NVVM dialect
        # types (nvvm.kernel attr).  Loading NVIDIA dialects is required until
        # IM has its own FuncOpConversion that avoids NVVM attributes.
        nvidia.load_dialects(ctx)

    @staticmethod
    def make_ttir(mod, metadata, options):
        skip = set(options.skip_passes)

        ttir_passes = [
            "inline",
            "triton-rewrite-tensor-descriptor-to-pointer",
            "canonicalize",
            "triton-reorder-broadcast",
            "cse",
            "symbol-dce",
            "triton-loop-unroll",
            "triton-licm",
            "triton-loop-aware-cse",
            "canonicalize",
            "cse",
        ]

        if options.im_persistent:
            # MUST be set here, not in make_ttgir: triton-licm runs in THIS stage,
            # and it is the only pass in the pipeline that hoists loads. Setting it
            # later meant the attribute existed but nothing had read it.
            #
            # Licenses triton-licm to hoist a load out of a loop that writes, when
            # the write provably lands on a different kernel pointer argument. Safe
            # here because pim_register_tensor refuses overlapping tensors, so two
            # pointer arguments are always distinct buffers. Named separately from
            # im.persistent so the assumption is visible in the IR rather than
            # implied by the kernel shape.
            mod.set_attr("im.noalias_args",
                         ir.builder(mod.context).parse_attr("1 : i64"))

        if _im_debug():
            _dump_stage(mod, "ttir_input", "ttir_input.mlir")

        pm = ir.pass_manager(mod.context)
        pm.enable_debug()
        passes.common.add_inliner(pm)
        passes.ttir.add_rewrite_tensor_descriptor_to_pointer(pm)
        passes.common.add_canonicalizer(pm)
        # NOT run on IM. CombineBroadcastMulReducePattern folds
        # reduce_add(broadcast(a)*broadcast(b)) into tt.dot, which this backend has
        # no lowering for at all (zero mentions in TritonIMToLLVM.cpp). In fp16 it
        # also splats an f32 zero into an f16 accumulator and fails the verifier at
        # standard.py:293. Measured byte-identical LLIR with and without on seven
        # configs (matmul k-packed, matmul 128^3, matvec, conv 3x3/1x1/stride-2,
        # SIMDRAM conv), so dropping it changes nothing that works today.
        if "triton-reorder-broadcast" not in skip:
            passes.ttir.add_reorder_broadcast(pm)
        passes.common.add_cse(pm)
        passes.common.add_symbol_dce(pm)
        if "triton-loop-unroll" not in skip:
            passes.ttir.add_loop_unroll(pm)
        if "triton-licm" not in skip:
            passes.ttir.add_triton_licm(pm)
            passes.ttir.add_loop_aware_cse(pm)
            passes.common.add_canonicalizer(pm)
            passes.common.add_cse(pm)
        pm.run(mod, "make_ttir")

        builder = ir.builder(mod.context)
        # ── IM-specific module attributes (clean, readable names) ──
        mod.set_attr("im.num-banks", builder.get_int32_attr(options.num_banks))
        mod.set_attr("im.arch", builder.get_string_attr(options.arch))
        # Step 4 schedule channel. The pass rejects a malformed or unmatched
        # schedule, so a typo fails the compile instead of quietly measuring the
        # classifier's default.
        if options.im_schedule:
            mod.set_attr("im.schedule", builder.parse_attr(options.im_schedule))
        if options.im_bg_interleave:
            mod.set_attr("im.bg_interleave", builder.parse_attr("1 : i64"))
        if options.im_persistent:
            mod.set_attr("im.persistent", builder.parse_attr("1 : i64"))
            mod.set_attr("im.noalias_args", builder.parse_attr("1 : i64"))
        _SCHEMES = {"striped": 1, "interleaved": 2}
        _ALIGNS = {"dq": 1, "global-row": 2}
        if options.im_layout_scheme not in _SCHEMES:
            raise ValueError(
                f"im_layout_scheme={options.im_layout_scheme!r}; "
                f"expected one of {sorted(_SCHEMES)}")
        if options.im_placement_align not in _ALIGNS:
            raise ValueError(
                f"im_placement_align={options.im_placement_align!r}; "
                f"expected one of {sorted(_ALIGNS)}")
        mod.set_attr("im.layout_scheme",
                     builder.parse_attr(f"{_SCHEMES[options.im_layout_scheme]} : i64"))
        mod.set_attr("im.placement_align",
                     builder.parse_attr(f"{_ALIGNS[options.im_placement_align]} : i64"))
        if options.im_row_values:
            if int(options.im_row_values) < 1:
                raise ValueError(
                    f"im_row_values={options.im_row_values!r}; must be positive")
            mod.set_attr("im.row_values",
                         builder.parse_attr(f"{int(options.im_row_values)} : i64"))
        if options.im_dq_bits:
            if int(options.im_dq_bits) < 1:
                raise ValueError(
                    f"im_dq_bits={options.im_dq_bits!r}; must be positive")
            mod.set_attr("im.dq_bits",
                         builder.parse_attr(f"{int(options.im_dq_bits)} : i64"))
        if options.im_bank_split:
            parts = [int(v) for v in str(options.im_bank_split).split(",") if v != ""]
            if not parts or any(v < 1 for v in parts):
                raise ValueError(
                    f"im_bank_split={options.im_bank_split!r}; want comma-separated "
                    f"positive lane counts, e.g. \"4,8\"")
            mod.set_attr("im.bank_split",
                         builder.parse_attr("array<i64: " + ", ".join(map(str, parts)) + ">"))
        if options.im_bank_axis >= 0:
            mod.set_attr("im.bank_axis",
                         builder.parse_attr(f"{options.im_bank_axis} : i64"))
        # # ── TritonGPU plumbing ──
        # mod.set_attr("ttg.num-warps", builder.get_int32_attr(options.num_warps))
        # mod.set_attr("ttg.num-ctas", builder.get_int32_attr(options.num_ctas))
        # mod.set_attr("ttg.threads-per-warp", builder.get_int32_attr(options.num_banks))

        if _im_debug():
            _dump_stage(mod, "ttir", "ttir.mlir")
        metadata["_ttir_passes"] = ttir_passes
        return mod

    @staticmethod
    def make_ttgir(mod, metadata, options):
        skip = set(options.skip_passes)

        ttgir_passes = [
            f"convert-triton-to-tritongpu{{target=im:{options.arch} "
            f"num-warps={options.num_warps} "
            f"threads-per-warp={options.num_banks} "
            f"num-ctas={options.num_ctas}}}",
            "rewrite-im-layout",
            "im-operand-residency-layout",
            "tritongpu-remove-layout-conversions",
            "tritongpu-reduce-data-duplication",
            "canonicalize",
            "cse",
            "loop-invariant-code-motion",
            "canonicalize",
            "cse",
        ]

        pm = ir.pass_manager(mod.context)
        pm.enable_debug()
        passes.ttir.add_convert_to_ttgpuir(
            pm, f"im:{options.arch}",
            options.num_warps,     # always 1
            options.num_banks,     # threads_per_warp ← num_banks
            options.num_ctas,
        )
        if "rewrite-im-layout" not in skip:
            passes.convert.add_rewrite_im_layout(pm)
        if "im-operand-residency-layout" not in skip:
            passes.convert.add_im_operand_residency_layout(pm)
        if "tritongpu-remove-layout-conversions" not in skip:
            passes.ttgpuir.add_remove_layout_conversions(pm)
        if "tritongpu-reduce-data-duplication" not in skip:
            passes.ttgpuir.add_reduce_data_duplication(pm)
        passes.common.add_canonicalizer(pm)
        passes.common.add_cse(pm)
        if "mlir-licm" not in skip:
            passes.common.add_licm(pm)
            passes.common.add_canonicalizer(pm)
            passes.common.add_cse(pm)
        pm.run(mod, "make_ttgir")

        if _im_debug():
            _dump_stage(mod, "ttgir", "ttgir.mlir")
        metadata["_ttgir_passes"] = ttgir_passes
        return mod

    @staticmethod
    def make_llir(src, metadata, options):
        llir_passes = [
            "loop-invariant-code-motion",
            "convert-scf-to-cf",
            "convert-triton-im-to-llvm",
            "convert-index-to-llvm",
            "convert-arith-to-llvm",
            "convert-cf-to-llvm",
            "canonicalize",
            "cse",
        ]

        mod = src
        metadata["name"] = mod.get_entry_func_name()
        skip = set(getattr(options, "skip_passes", ()) or ())
        pm = ir.pass_manager(mod.context)
        pm.enable_debug()
        if "mlir-licm" not in skip:
            passes.common.add_licm(pm)
        # BEFORE scf-to-cf: afterwards the tile loop's back edge is a branch and
        # finding it means recovering the structure that conversion discards. No-op
        # unless the module is marked persistent. The call it inserts used to blow
        # the stack in the IM conversion's membar analysis, which is fixed in
        # Membar.cpp, so persistent cycle numbers are quotable again.
        if "im-tile-boundary" not in skip:
            passes.convert.add_im_tile_boundary(pm)
        passes.convert.add_scf_to_cf(pm)
        passes.convert.add_convert_triton_im_to_llvm(pm)
        passes.convert.add_index_to_llvmir(pm)
        passes.convert.add_arith_to_llvmir(pm)
        passes.convert.add_cf_to_llvmir(pm)
        passes.common.add_canonicalizer(pm)
        passes.common.add_cse(pm)
        pm.run(mod, "make_llir")

        if _im_debug():
            _dump_stage(mod, "llvm_dialect", "llvm_dialect.mlir")

        llvm.init_targets()
        context = llvm.context()
        llvm_mod = llvm.to_module(mod, context)

        metadata["shared"] = 0
        metadata["profile_scratch_size"] = 0
        metadata["profile_scratch_align"] = 1
        llir = str(llvm_mod)
        # Strip NVIDIA artifacts injected by the shared FuncOpConversion.
        llir = re.sub(r"\bptx_kernel\s+void\b", "void", llir)
        llir = re.sub(
            r'^attributes\s*#\d+\s*=\s*\{[^}]*nvvm[^}]*\}\s*$', "",
            llir, flags=re.MULTILINE,
        )
        llir = re.sub(r'\)\s*#\d+\s*\{', ") {", llir)

        if _im_debug():
            _dump_stage(llir, "llir", "llir.ll")
            # Emit commands.sh with all three triton-opt pipeline commands.
            _dump_commands([
                {
                    "title": "Stage 1 — TTIR",
                    "note": "Module attributes (im.num-banks etc.) are set "
                            "after this pipeline in Python; ttir.mlir already "
                            "has them.",
                    "input": "im_debug/ttir_input.mlir",
                    "output": "im_debug/ttir.mlir",
                    "passes": metadata.get("_ttir_passes", []),
                },
                {
                    "title": "Stage 2 — TTGIR",
                    "input": "im_debug/ttir.mlir",
                    "output": "im_debug/ttgir.mlir",
                    "passes": metadata.get("_ttgir_passes", []),
                },
                {
                    "title": "Stage 3 — LLVM Dialect",
                    "input": "im_debug/ttgir.mlir",
                    "output": "im_debug/llvm_dialect.mlir",
                    "passes": llir_passes,
                },
            ])
        metadata.pop("_ttir_passes", None)
        metadata.pop("_ttgir_passes", None)
        return llir

    def add_stages(self, stages, options, language):
        if language == Language.TRITON:
            stages["ttir"] = lambda src, metadata: self.make_ttir(src, metadata, options)
            stages["ttgir"] = lambda src, metadata: self.make_ttgir(src, metadata, options)
        stages["llir"] = lambda src, metadata: self.make_llir(src, metadata, options)
